name: Deploy static content to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write  # Required for authentication with GitHub OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Optimize images
        run: |
          npm install -g imagemin-cli
          imagemin src/images/* --out-dir=dist/images || echo "Image optimization failed, but continuing."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
